project:
  type: book

book:
  site-url: https://qiufei.site/rbook
  search: true
  navbar: 
    left:
      - text: "首页"
        href: https://qiufei.site
  title: R语言数据分析
  # 设置网站图标
  favicon: profile.jpg
  cover-image: profile.jpg
  reader-mode: true
  author: 邱飞
  date: 3/23/2024
  body-footer: |
    邱飞 &copy; 2008-2024  <a href="https://beian.miit.gov.cn/" target="_blank">浙ICP备 2024072710号-1</a>  <a href="https://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33021202002511" target="_blank">浙公网安备 33021202002511号</a>
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
     light: journal
     dark: cyborg
  # pdf:
  #   documentclass: scrreprt



  